substitutions:
  device_name: "athom-mini-switch"
  friendly_name: "Athom Mini Switch"
  project_name: "athom.mini-switch"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {}

captive_portal:


switch:
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"
      
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO4
      inverted: true
      
  - platform: gpio
    pin: GPIO13
    id: mini_relay
    name: "${friendly_name}"
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led
    

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
    name: "${friendly_name} Power Switch"
    filters:
      - delayed_on: 100ms
    on_state:
      then:
        - switch.toggle: mini_relay
        
  - platform: gpio
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Power Button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: mini_relay
      - timing:
          - ON for at least 4s
        then:
          - switch.turn_on: restart_switch
          
  - platform: status
    name: "${friendly_name} Status"
    
time:
  - platform: sntp