substitutions:
  device_name: "athom-garage-door"
  friendly_name: "Athom Garage Door"
  project_name: "athom.garage-door"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    name: "${friendly_name} sensor"
    id: "Sensor"
    disabled_by_default: true
    filters:
      - delayed_on: 20ms

  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
          
switch:
  - platform: gpio
    pin: GPIO5
    name: "${friendly_name} Relay"
    id: "relay"
    disabled_by_default: true
    on_turn_on:
     - switch.turn_on: relay_led
     - delay: 1s
     - switch.turn_off: relay
     - switch.turn_off: relay_led
    
    
  - platform: gpio
    id: relay_led
    pin:
      number: GPIO12
    
cover:
  - platform: template
    device_class: garage
    name: "${friendly_name}"
    lambda: |-
      if (id(Sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.toggle: relay
    close_action:
      - switch.toggle: relay
    
 