substitutions:
  device_name: "athom-rgbw-controller"
  friendly_name: "Athom RGBW Controller"
  project_name: "athom.rgbw-controller"
  project_version: "1.0"
  button_toggle: "true"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.


captive_portal:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: gpio
    name: "${friendly_name} Button"
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
    on_click:
      - if:
          condition:
            lambda: "return ${button_toggle} == true;"
          then:
            - light.toggle: leds

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"

switch:
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO13

light:
  - platform: rgbw
    name: "${friendly_name}"
    id: leds
    default_transition_length: 250ms
    red: red_output
    green: green_output
    blue: blue_output
    white: white_output
    color_interlock: false

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
